[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NAO Docs"
authors = [{name = "hasith", email = "hasith.abayakoon@gmail.com"}]
dynamic = ["version", "description"]
